version: "3.4"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_pg_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_pg_pass}
      POSTGRES_DB: ${POSTGRES_DB:-app}

  php:
    build: ${PWD}/docker/php
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9009
    volumes:
      - ${PWD}/service1:${S1_DOCKER_APP_PATH}
      - ${PWD}/service2:${S2_DOCKER_APP_PATH}
      - /etc/timezone:/etc/timezone:ro
      - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${PWD}/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: ${S1_DOCKER_APP_PATH}
    depends_on:
      - db

  nginx:
    image: nginx:mainline-alpine
    ports:
      - ${S1_HTTP_PORT:-80}:80
      - ${S2_HTTP_PORT:-81}:81
    volumes:
      - ${PWD}/service1:${S1_DOCKER_APP_PATH}
      - ${PWD}/service2:${S2_DOCKER_APP_PATH}
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:16-alpine
    volumes:
      - ${PWD}/service1:${S1_DOCKER_APP_PATH}
      - ${PWD}/service2:${S2_DOCKER_APP_PATH}
    working_dir: ${S1_DOCKER_APP_PATH}
    command: yarn watch
    depends_on:
      - nginx

  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
volumes:
  db-data:
  eventstore-volume-data:
  eventstore-volume-logs:
